package thread.game2;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class MoleJFrame extends javax.swing.JFrame {

    ImageIcon mole1 = new ImageIcon(getClass().getResource("/thread/game2/mole1.png"));
    ImageIcon mole2 = new ImageIcon(getClass().getResource("/thread/game2/mole2.png"));
    ImageIcon mole3 = new ImageIcon(getClass().getResource("/thread/game2/mole3.png"));
    ImageIcon mole4 = new ImageIcon(getClass().getResource("/thread/game2/mole4.png"));
    ImageIcon hole = new ImageIcon(getClass().getResource("/thread/game2/hole.png"));
    
    ImageIcon[] movie = {hole, mole1, mole2, mole3, mole2, mole1, hole};
    MolePlay mp1, mp2, mp3;
    public MoleJFrame() {
        initComponents();
        mp1 = new MolePlay(m1, 1000);
        mp2 = new MolePlay(m2, 200);
        mp3 = new MolePlay(m3, 500);
        
        mp1.start();
        mp2.start();
        mp3.start();
    }
    
    class MolePlay extends Thread {
        private JLabel label;
        private int idx;
        private int delay;
        boolean hit;
        private int hitcount;
        private AudioPlayer audio;
        MolePlay(JLabel label, int delay) {
            this.label = label;
            this.delay = delay;
        }

        @Override
        public void run() {
            while(true) {
                if(hit) {
                    if(idx % movie.length == 2 || idx % movie.length == 3 || idx % movie.length == 4) {
                        audio = new AudioPlayer();
                        audio.loadAudio("punch.wav", this);
                        audio.setPlayCount(-1);// 播放次數
                        audio.play();

                        label.setIcon(mole4);
                        try {
                            Thread.sleep(2000);
                        } catch (Exception e) {
                        }
                        idx = 0;
                        if(++hitcount == 3) {
                            label.setIcon(hole);
                            break;
                        }
                    }
                    hit = false;
                } else {
                    idx++;
                    label.setText(String.valueOf(idx % movie.length));
                    label.setIcon(movie[idx % movie.length]);
                    try {
                        Thread.sleep(delay);
                    } catch (Exception e) {
                    }
                }
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m1 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        m1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thread/game2/hole.png"))); // NOI18N
        m1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m1MousePressed(evt);
            }
        });

        m3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thread/game2/hole.png"))); // NOI18N
        m3.setToolTipText("");
        m3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m3MousePressed(evt);
            }
        });

        m2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thread/game2/hole.png"))); // NOI18N
        m2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(m1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m2)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(m1)
                        .addGap(32, 32, 32)
                        .addComponent(m3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(m2)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MousePressed
        mp1.hit = true;
    }//GEN-LAST:event_m1MousePressed

    private void m2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MousePressed
        mp2.hit = true;
    }//GEN-LAST:event_m2MousePressed

    private void m3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m3MousePressed
        mp3.hit = true;
    }//GEN-LAST:event_m3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoleJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    // End of variables declaration//GEN-END:variables
}
