/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thread.game;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author student
 */
public class BingoJFrame extends javax.swing.JFrame {

    ImageIcon apple = new ImageIcon(getClass().getResource("/thread/game/apple.png"));
    ImageIcon bar = new ImageIcon(getClass().getResource("/thread/game/bar.png"));
    ImageIcon bell = new ImageIcon(getClass().getResource("/thread/game/bell.png"));
    ImageIcon luckyseven = new ImageIcon(getClass().getResource("/thread/game/luckyseven.png"));
    ImageIcon mango = new ImageIcon(getClass().getResource("/thread/game/mango.png"));
    ImageIcon orange = new ImageIcon(getClass().getResource("/thread/game/orange.png"));
    ImageIcon star = new ImageIcon(getClass().getResource("/thread/game/star.png"));
    ImageIcon watermelon = new ImageIcon(getClass().getResource("/thread/game/watermelon.png"));

    ImageIcon[] list = {apple, bar, bell, luckyseven, mango, orange, star, watermelon};

    public BingoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thread/game/apple.png"))); // NOI18N

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thread/game/apple.png"))); // NOI18N

        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thread/game/apple.png"))); // NOI18N

        b1.setFont(new java.awt.Font("新細明體", 0, 48)); // NOI18N
        b1.setText("Play");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a1)
                        .addGap(53, 53, 53)
                        .addComponent(a2)
                        .addGap(60, 60, 60)
                        .addComponent(a3)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1)
                    .addComponent(a2)
                    .addComponent(a3))
                .addGap(40, 40, 40)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    AudioPlayer audio;
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // apple, bar, bell, luckyseven, mango, orange, star, watermelon
        Bingo bingo = new Bingo();
        bingo.start();

        audio = new AudioPlayer();
        audio.loadAudio("bingo2b.wav", this);
        audio.setPlayCount(-1);// 播放次數
        audio.play();
    }//GEN-LAST:event_b1ActionPerformed

    class Bingo extends Thread {

        @Override
        public void run() {
            for (int i = 1; i <= 320; i++) {
                int n1 = new Random().nextInt(list.length);
                int n2 = new Random().nextInt(list.length);
                int n3 = new Random().nextInt(list.length);
                a1.setIcon(list[n1]);
                a2.setIcon(list[n2]);
                a3.setIcon(list[n3]);
                try {
                    Thread.sleep(10);
                } catch (InterruptedException ex) {
                }
            }
            audio.stop();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BingoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JButton b1;
    // End of variables declaration//GEN-END:variables
}
